// ==UserScript==
// @name         Font.master
// @version      1.122
// @description  Font.master
// @author       TKA
// @match        *://*/*
// @exclude      https://*.oasistrek.com/*
// @exclude      https://m.facebook.com/*
// @grant        none
// @run-at       document-start
// @downloadURL			https://github.com/auterrykp/Fonts/raw/refs/heads/master/font-master.js
// @updateURL				https://github.com/auterrykp/Fonts/raw/refs/heads/master/font-master.js
// ==/UserScript==

(function () {
  const style = document.createElement('style');
  style.textContent = `


/* Google Fonts */
@import url('https://fonts.googleapis.com/css2?family=Murecho:wght@300&family=Noto+Sans+HK:wght@300&family=Noto+Serif+HK:wght@400&display=swap');


/* Font Variables */
:root {
  --main-font: 'PingFangSCRegular.EN','PingFangSC-Light','Noto Sans HK','GenSenMaruGothicTW-Light';
  --jp-font: 'Murecho';
  --alt-font: 'CathaySans_Lt','PingFangSC-Light','Noto Sans HK','GenSenMaruGothicTW-Light';
  --serif-font: 'Iowan－BT','Noto Serif HK';
}


/* Apply font ONLY to content elements */
html * {
  font-family: var(--main-font) !important;
  letter-spacing: 0.025em !important;
  font-size-adjust: 0.52 !important;
}


/* Japanese content override */
html[lang*="ja"] * {
  font-family: var(--jp-font) !important;
  letter-spacing: 0.025em !important;
  font-size-adjust: 0.52 !important;
}


/* Apply serif font only to European language pages
:is(html[lang*="en"],
html[lang*="fr"],
html[lang*="de"],
html[lang="es"],
html[lang="it"],
html[lang="pt"],
html[lang="nl"],
html[lang="sv"],
html[lang="no"],
html[lang="da"],
html[lang="fi"],
html[lang="pl"],
html[lang="cs"],
html[lang="sk"],
html[lang="sl"],
html[lang="ro"],
html[lang="bg"],
html[lang="hr"],
html[lang="hu"],
html[lang="el"]) * {
  font-family: var(--serif-font) !important;
}

*/


/* Preserve native icon fonts for common icon-like elements */
body :is(
  [class*="fa-"],
  [class="fa"],
  [class="fas"],
  [class="fal"],
  [class="fab"],
  [class="icon"],
  [class*="icon-"],
  [class*="cart"],
  [class*="arrow"],
  [class*="vjs"],
  [class*="glyph"],
  [class*="material-icons"],
  .docon,
  .ji,
  .tb-ifont,
  .google-symbols,
  i,
  svg,
  path,
  img,
  ::before,
  ::after
) {
  font-family:
    'Font Awesome 6 Free', 'Font Awesome 5 Pro', 'Font Awesome 5 Free', 'FontAwesome',
    'ichiba-icon-font', 'Material Icons', 'Google Material Icons', 'bootstrap-icons',
    'Material-Design-Iconic-Font', 'Flaticon', 'icons', 'Ionicons', 'global-iconfont',
    'icomoon', 'font-icons', 'Line Awesome Free', 'simple-line-icons', 'entypo',
    'HSBCIcon-Font', sans-serif !important;
}



/* Font-Faces */
@font-face {
  font-family: 'PingFangSC-Light';
  src: url('https://rawcdn.githack.com/auterrykp/Fonts/9ac3fde5673ecd0bdd630309832c1e216943a367/PingFangSC-Light.woff2') format('woff2');
}

@font-face {
  font-family: 'PingFangSCRegular.EN';
  src: url('https://rawcdn.githack.com/auterrykp/Fonts/8e9a7bf1a446333b8de3cbfec422046d4e7b8fbd/PingFangSCRegular.woff2') format('woff2');
}

@font-face {
  font-family: 'CathaySans_Lt';
  src: url('https://rawcdn.githack.com/auterrykp/Fonts/e321a95fb49e932beb9afdb6b7870a75e99323a6/CathaySans_Lt.woff2') format('woff2');
}

@font-face {
	font-family: 'Iowan－BT';
    src: url(https://rawcdn.githack.com/auterrykp/Fonts/refs/heads/master/iowan.woff) format('woff');
    unicode-range: U+00-2B11,U+EBE7-FB02;
}

@font-face {
	font-family: 'GenSenMaruGothicTW-Light';
    src: url(https://rawcdn.githack.com/auterrykp/Fonts/425066cd1e3c20623619856b8b2810f204367e4c/GenSenMaruGothicTW-Light-07OCT21.woff2) format('woff2');
    unicode-range: U+2000-206F,U+2100-214F,U+2E80-2EFF,U+3000-303F,U+3400-4D8F,U+4E00-9FFF,U+F900-FAFF,U+FF00-FFEF;
}


/* master.css */



.page-article .border-primary,#postContent .entry-content h2,
p.break-words,.incontent p,dfn+div p,article.post-wrap .single-entry p,#postContent p[style].post-page .post-body-article .post-body-content p {


  max-width: 95% !important;
  width: 95% !important;
  margin-right: auto !important;
  margin-left: auto !important;
  box-sizing: border-box !important;
  text-align: justify!important;
  text-justify: inter-word !important
  color: #e4e6eb !important

}


.incontent h2, #bkg_wrapper h1 {
font-weight: bold !important;
color: #e4e6eb !important;

}

/*hko*/
.post .title,#postContent p:not(strong),#GeneralSituation_header,#GeneralSituation_content p,#forecastPeriod p,#forecastDesc p,#forecastContent p,#forecastPeriod,.area_weather_forecast>div:nth-child(2)>div:nth-child(1)>div .header,.area_weather_forecast>div:nth-child(2)>div:nth-child(1)>div:last-child,#fnd_general,.header.gs {
font-size: 1.2rem !important
}

/*oasis*/
html[xmlns="http://www.w3.org/1999/xhtml"],[lang="zh-Hant"] {
  max-width: 98% !important;
  margin-right: auto !important;
  margin-left: auto !important;
  box-sizing: border-box !important;
}


/*Hide elements*/

#AD-970x250-AD1,
#App-deepLink,
#MStoriesTray,
#___gcse_0,
#__next .placeholder-ad,
#_idpfLP_mdl.idpfLP_mdl,
#abtest_banner_li,
#ad-fullscreen,
#ad-lite-recommend-wrap,
#ad-overlay,
#adGeek-slot-div-gpt-ad-1585561206369-0[style],
#ad_banner_pos1,
#ad_unit,
#adsDefinitions,
#afscontainer1,
#appDlBanner-upper.appDlBanner,
#archives-2,
#aswift_0_anchor,
#aswift_0_expand,
#aswift_1_host,
#at4-share,
#aw0,
#banner-close-monkey,
#banner-exit,
#bbsearch,
#body-container .sd_nav,
#bottomRectangleContainer,
#branch-banner-iframe,
#category-posts-2,
#category-posts-3,
#comment-plugin-page-level,
#comments-slot,
#commonConts,
#comp-cool-britannia-1,
#config_mobile-1x2-inreadExtra_Entertainment,
#contentSponsorshipAd,
#contents .pos-infeed,
#covid-tracker-takeover,
#cto_banner_content,
#facebookComments,
#float_fb_plugin,
#footer .container[data-v-7a80e4fa],
#footer-menu.footer-menu-wrap,
#footerG,
#footer_bottom,
#footer_nav,
#ftalt3636127,
#gdpr-dialog,
#geniee_overlay,
#global-container .right-col,
#global-container div.banner-background,
#global-container div.sr2-jobs-layer-anchor,
#global_bnr_wrap,
#google-center-div,
#google_ads_frame1,
#google_ads_iframe,
#google_center_div,
#google_image_div,
#gwd-ad,
#herald-responsive-header .container,
#imgzone,
#inread-standard-passback-unit,
#jp-relatedposts,
#kpftw,
#lcs-stack-sticky-bottom,
#links-row-1,
#logly-lift-widget,
#main-content .ad-slot--mobile,
#main-content .advert.ad-slot,
#main-content .article-page-outer__top-ad,
#main-content .smart-banner,
#main-content .top-ad--hidden,
#main-content.notification__message,
#maincontent .navbar-fixed-top,
#maincontent p iframe,
#mainportal,
#masthead .site-description,
#mhd_banner_wrapper,
#mobile-1x2-inread,
#mobile-1x2-inreadExtra,
#mobile-300x250-beforeContent,
#mobile_banner_native_1,
#nativead_0,
#news-slider,
#onesignal-slidedown-container,
#orb-aside,
#orb-header,
#page .mobileMenu,
#page .nonMobileMenu,
#page .site-bar,
#page-wrap>#footer,
#page-wrap>#sidebar,
#pixad891d,
#poi-booking-picker div.mask,
#popover-container.s1wau3gh-0.iDGcev,
#postArticle,
#postHeadBtns.clearfix,
#post_under_ads,
#reactDockedPopup,
#readmore,
#recent-posts-2,
#rf-js-scroll-top,
#right-fixed.art-w65-right,
#righteditorchoice,
#ruby-back-top i,
#sda-LREC2,
#sda-WFPAD,
#search-2,
#sharebar.sharebtn,
#shareft.sharebtn,
#single-post-list,
#site-navigation.urbanlife,
#siteHeader.siteHeader,
#slide-wrap.slide-wrap,
#spotlight,
#ssm1.ssm,
#sub_categories_widget-4,
#sub_categories_widget-5,
#subscribe_mobile_cont,
#tag_cloud-2,
#talkappi-chat-greeting,
#topHeaderBarFX.fixed-bar,
#topInAppNotificationBanner,
#uni300,
#user-post,
#video-widget-3,
#whatsapp_promo_btn,
#whatsapp_promo_btn_close,
#widget_tptn_pop-2,
#zi_ad_article_below_title,
.-mt-4.-mx-3,
.AdContainer-sc-8mk8fx-0,
.COOzN.MnWb5.YT6rB,
.DCpAF,
.FeatureArea,
.HYSJg,
.KGiwt::before,
.LazyLoad.mt-4.l7v9z99,
.LifeTool__listItem::after,
.LifetoolItem__unsetStatus,
.MFV,
.MagAndSpArea,
.MqMobileTablet,
.PdwC2 .Ppjfr.UE9AK.wdOqh,
.PremiumFirst.js-PremiumFirst,
.RWDContainer.share_box_m,
.RichSmartAppBanner,
.SupportPeron,
.U9Cd6d,
._2p3a,
._2rbw,
._3-8o,
._3flVZe-,
._3t1IIUwX87Q7giYt9CBgsT,
._56q9,
.__survey-bar.survey-bar-article-under,
._popIn_recommend_container,
._vi6,
.ad-box[style],
.ad-flyingcarpet1-placeholder,
.ad-frame-fix,
.ad-tip,
.ad300,
.adContainer,
.adWrap,
.adWrap-articleHead,
.adWrap.adWrap-articleHead,
.ad_google_LREC,
.adncon,
.adnol,
.ads-parallax-fixed,
.adsbyfalcon,
.adsbygoogle,
.advert__holder,
.amp-animate,
.amp-fx-flying-carpet-title,
.area-menu.desktop,
.article-body__contents-pr-primary,
.article-details-type--more-on-this,
.article-details-type--newsletter,
.article-divider--default::after,
.article-divider--default::before,
.article-footer,
.article-list__inline-ad,
.article-sec,
.article>.wrapper .mobile-wide-ad-container-1,
.axslot.lrct_inject gemini,
.b0KoTc.B4GxFc,
.bOA-DQ,
.banner.u-inner-space-t-XS,
.bbc-1dg7u9h.e10yv9r13 div,
.bg-white.rounded-t-lg,
.block--revive-adserver-zone-block,
.bnextmeida-banner,
.bottom-header__urbanlife,
.boxLayou01,
.boxShare,
.branch-banner-button-co,
.btnClose,
.btnNext,
.btnPrev,
.btnWrap.shareEl,
.btn_clip.btn_clip_add,
.c-detail_under,
.c-download-banner.u-md-up-hidden.active,
.c-lang,
.c-posts__eyecatch,
.c-ranking,
.cHKvki.sc-1jdnux-0.cMdVCV,
.caas-da,
.caption2.native_ad,
.caption5,
.card-box.adshow.hasAuthor,
.card-box.fb-box,
.card-box.mobile-shareBox,
.card.center.bold.topic,
.clip_widget,
.code-block,
.col-lg-8 p.article-page-link__inner-aritcle-lead,
.col-xs-1.col-sm-1.col-md-1.share-button,
.col-xs-12.col-sm-1.col-md-1.share-button,
.columns-right,
.commentDetail,
.component.feed.clearfix,
.component.newsletter-callout.newsletter-inline-signup,
.component.subscribe-callout,
.container-fluid.main.clearfix>div.top_banner_ad,
.container-inner>.pad,
.container.container--pagetop.show,
.content--outstream-1,
.content-promote,
.content-related,
.contentLastLrecGroup,
.css-14akkwd,
.css-1dbjc4n.r-1g40b8q,
.custom-button.fb-share.custom-button-mobile,
.custom-html-widget,
.cwBzbR,
.daily_search,
.di8g3.YGvGmb,
.dtivfw8,
.dzlctlu.hidden,
.e1e90g5r0,
.elementor-2332 .elementor-element.elementor-element-60cf76e8,
.elementor-grid-0 .elementor-grid,
.embed-responsive-1by1,
.expLink,
.extrabox,
.eyXLr.wUAXj,
.fb-like,
.fb-page,
.fb-share[data-v-14c8653e],
.fb_iframe_widget,
.feature_comment.allsize,
.fj-navbar-mobile.navbar-inverse.affix,
.fl-node-5bad2b23b88d6,
.footer-logo-container,
.footerBanner,
.footerInduction,
.footerInner,
.footerPromo,
.footerTop.ng-scope,
.gaOqrY,
.gnav201606,
.googleAds-frame,
.google_ads_iframes,
.gpc-c_r,
.gpt_ads_nobg,
.gpt_ads_title,
.gyHIoS,
.hJKzIb,
.hashtags-title,
.header-ad,
.header-ad-fixed,
.header-author-info,
.header-fixed-area,
.herald-ad,
.home-page__global-menu-container,
.home-recap,
.homepage__footer-ad-container.footer-ad-container,
.hor-share.computer_hide,
.hotnews,
.i-amphtml-element,
.i-amphtml-layout-fixed,
.icons_inner,
.icons_wrapper,
.ifdlyq,
.img-responsive.center-block,
.img_ad,
.indexCol06,
.indexCol07,
.indexTopInfo,
.info__sections.sections [data-v-7638e4bc],
.inline-ad-container,
.inline-ad-container[data-v-83913f50],
.inner-floating-container,
.inread-ad-container,
.instants_new_title_header,
.item_list>li[style].clearfix,
.j2bo2s-0.iIwWej,
.jXBtGs::after,
.jXBtGs::before,
.js-gdpr-consent-banner,
.js-gtm-article-detail-h2-2,
.kGuEDe.jctesQ,
.kiwi-ad-sticky-wrapper,
.kiwi-ad-wrapper-ypa-300x250.kiwi-loaded,
.kxpaYt,
.l-contents-block.l-contents-block--article-ranking-article,
.l-contents-block.l-contents-block--tie-up,
.l-contents-block.l-contents-block--tie-up-lg,
.l-globalFooter,
.left-menu.for-sp,
.listMod .hd:before,
.localArea,
.logo-wrap .bar,
.magazine-panel,
.magazine-selection,
.mpads,
.msthdtxt,
.mt-4.-mx-3,
.native_ad,
.navbar.navbar-default.df-nav,
.new_ad,
.newest-listing,
.news-videos-thumbnail,
.newsBlock,
.newsListBlock.right-box,
.ng-scope header-induction,
.nmg-popular-posts-list,
.nocontent.robots-nocontent,
.notification[data-v-409b0395],
.ob-widget-section,
.op-container .opLink-group,
.op-wrapper.fadeInDown,
.opinion-section[data-v-3733b8ec]:before,
.p-article-comments__link.u-font-sans,
.p-articleLatests,
.pace-done .navbar-top,
.page-container__top-ad,
.page-wrapper .page_title,
.page__layout-navbar .shrink-0.flex.items-center,
.pickupArea,
.pickupMain_image_text p,
.pixad2199d,
.pixnavbar__top-bar__pix-site,
.pixnet-happix-pilot__happix-notification__wrapper,
.pixnet-happix-pilot__launcher-bar-desktop__wrapper.action,
.pixnet-happix-pilot__special-notification,
.pluginSkinLight.pluginFontArial,
.popular-post,
.posMMON,
.posNM#posNM,
.post .related-posts,
.post-relative,
.post-tab,
.post_content.entry-content>div.youtube-container,
.postauthor-container,
.q0b9qr-1.hkdMLI,
.q0b9qr-2.eKySBQ,
.r-1n0xq6e,
.r-1pz39u2,
.rankArea,
.read-btn.text-white,
.read-cube-btn,
.recommendArea,
.related-articles-container,
.related_post_list,
.related_posts.posts.related_posts_mobile,
.related_posts.posts.video[data-v-14c8653e],
.relatedposts,
.right .box,
.right_widget_2023,
.row.ad-for-moblie,
.s1235pe5-0.crGWqZ,
.s1kbpv34-0.dKCxIJ,
.s1u9kosf-2.doxrbe,
.s1x15mdy-4.cjSTik.s1x15mdy-3.gckjTC,
.sc-1235pe5-0.kzjkId,
.sc-1x15mdy-2.sc-1x15mdy-3.flayJi.fYpuvk,
.sc-250a058f-0.bXMTTM,
.sc-4ev7nz-0.eoXNZh.mt-4.mb-3.l7v9z99,
.sc-5vyyvj-0.sc-1u9kosf-0.kGuEDe a,
.sc-bdfBwQ.jTtUyo.sc-1u9kosf-2.jctesQ,
.sc-bwzfXH.irAmUN.sc-bdVaJa.hDjqJr,
.sc-bwzfXH.loXcNn.sc-bdVaJa.iMnSNo,
.sc-e7260fca-0.dCJNLb,
.sc-fONwsr.jVIdGW,
.score-promotion-section .promotion-section,
.section-article-publish,
.section-article-tag,
.section-sns-share.section.clearfix.inner,
.share-article-vertical,
.share-btns.bg-white,
.share-tools--no-event-tag,
.share-widget.article-page__share-widget--mobile,
.share.share--lightweight.ghost-column,
.shareSocalBtn .tw,
.shareSocalBtn li .fb,
.share_btn.addthis_button_facebook,
.sharelink_icon,
.sidebar.widget-area,
.single-header .post-cat-info:before,
.single-sns.clearfix.mini,
.site-header-sticky-wrapper,
.smart-banner-container,
.smartbanner.smartbanner-android,
.social-logo-container,
.social-share.row,
.sp_foreign_banner,
.stick-share.nav-up,
.subscribe-bar-container,
.subscribe-cover img,
.tagBottom,
.text-overflowed.threeLine p,
.textAd__section[data-v-8d1ed43c],
.title-display.desktop-only,
.tm-floating-banner__contents,
.tmb_tn_ad_content,
.top-promo,
.trading_item_section.item_list_wrap,
.tuQOVc,
.u-mb-15,
.ui-tabs,
.uz-ar,
.uz-travel-star_pc,
.view_followus,
.viu_widget,
.vjs-error-display:before,
.vjs-ima3-ad-container,
.w11zjxzn,
.widget-odd.widget-5.widget.widget_text,
.widget.widget_pages,
.widget_custom_html,
.width.imgs_1,
.wp-post-author-wrap.wp-post-author-shortcode,
.wp_rp_twocolumns,
.wrapper__bottom.bottom,
.ytp-chrome-top-buttons,
.zZYga::after,
.zZYga::before,
.zeropadding #footer,
.zi_ad_article_below_title,
.zucks-widget-container,
[data-v-1a49529d].coronavirus,
[data-v-45e788e6],
[data-v-515deb48],
[data-v-f6a8331a].top-ad--hidden,
a.StyledLink-dda4ku-0.bOraUr,
a.appBtn,
a.fbShare,
a.hket-channel,
a.imageUploadLink,
a.script-toggle,
address.author_cards,
article#u_1d_2,
article._7i8m,
aside .report,
aside#search-3,
aside.outer-link,
aside.p-unit,
aside.sc-bdfBwQ.csOCgK,
aside.sc-bdfBwQ.hqqDhi,
aside.sc-bwzfXH.liBCIH.sc-bdVaJa.gyMRxJ,
aside.site-sidebar.sidebar-elements,
body div.presite_container,
body.category .archive-page-header .archive-title-wrap,
button.eFHJfn,
dd.editor_name,
div div.popular-section,
div#CoverPhoto,
div#at-share-dock,
div#banners1,
div#banners2,
div#container>div#sub,
div#content-sidebar,
div#div-gpt-ad-3,
div#fancybox-buttons,
div#fixedSnsSetPg,
div#foot-common,
div#gotop,
div#js-gdpr-consent-banner,
div#kpftwbg,
div#langselect-container,
div#ldynavbar,
div#mhd_header_sp,
div#onesignal-popover-container,
div#page_wrapper>div[style],
div#related_header,
div#respond,
div#search-container.search-box-wrapper,
div#section-title>p#update,
div#share_wrap,
div#sharebuttons,
div#smartbanner,
div#sns_side_wrap,
div#sub,
div#tabber,
div.ContactBox.Mobile,
div.HTMLBlock,
div.Header__contentWrapper,
div.HomeSchoolContainer,
div.HomeVideoContainer,
div.MFV,
div.Mobile.FooterWidgetInnerView,
div.ScrollButton.is-show,
div.SponsorBox,
div.THISISANADHERE,
div.Z_Gl2,
div._4bSq7,
div._52z5._451a.mFuturePageHeader._1uh1.firstStep.titled,
div.a-button-banner,
div.ad-block,
div.ad-box-auto,
div.ad-content,
div.ad-flying-carpet,
div.ad_left_bottom,
div.adhesion-ad.mobile-ad,
div.ads-para-container,
div.adsense-top,
div.af_space_567506304952,
div.appBanner,
div.app_banner,
div.area-menu.mobile,
div.article-body-aside.col-lg-3,
div.article-comment-wrapper,
div.article-link__img,
div.article-paragraph>i,
div.article-pr,
div.article-ribbon,
div.article-sns-icon,
div.article-tag.-label,
div.axslot.axsense,
div.banner-300,
div.banner-320,
div.big_ad,
div.branch-banner-button-container,
div.btnApp,
div.cc-window.cc-floating,
div.cmt-top.cmt-top-old,
div.col-md-28.sidebar,
div.col-xs-12.top-ads.superBanner_2,
div.colophon,
div.column--secondary,
div.comment-box,
div.comment-container,
div.content-related-container,
div.cookie_policy,
div.corner-btns-container,
div.cover-apps,
div.css-rfboy2,
div.details__topics-ad,
div.download a,
div.download>p,
div.entry-content.herald-entry-content>iframe[style],
div.expSpotImage,
div.eyz1oe-0,
div.feature-slider,
div.featured-block-bottom,
div.fixed-box.up,
div.float-relate,
div.floatingWindow.ng-scope,
div.footer-container,
div.footer-mobile.clearfix,
div.go_share.share_box_bottom,
div.googleAds-frame.googleAds-letstop-sp-header,
div.googleAds-frame.googleAds-style-sp-header,
div.hashtags-container,
div.header-num,
div.headerInduction,
div.header__sitename,
div.heateor_sss_mobile_footer,
div.heho-social-share .post-header-wrapper,
div.hot-articles.hot-articles-section-1,
div.hot-articles__main,
div.in-read-ad-sticky-wrapper,
div.inline-ad,
div.instants_new_title_header-top,
div.j2bo2s-0,
div.jetpack-likes-widget-wrapper,
div.js-cookie-disclaimer,
div.js-wrapper>div.top-banner,
div.kijiSns,
div.l-contents-block.l-contents-block--schedule,
div.link-to-app,
div.listing_top_highlight,
div.magazine-ad,
div.modTheme,
div.moduletable.span12,
div.more-title-en.hide-on-desktop,
div.navigation-container,
div.near_article,
div.ob-widget.ob-strip-layout.CRMB_1,
div.ob_what,
div.octopus.related-container.horizontal-padding-cleaner,
div.ol_footer_wrapper,
div.only_mobile,
div.page_contain,
div.page_contain1,
div.photo-credit,
div.pixnet-happix-pilot__launcher-bar,
div.pixnet-happix-pilot__sticky-box,
div.placeholder-ad,
div.pos-infeed,
div.post-article_header,
div.post-article_info,
div.post-pagination,
div.post-sub,
div.postauthor-top,
div.presite_containerm,
div.promotepagesection,
div.pubdate.sc-bwzfXH.loXcNn.sc-bdVaJa.jJqEVj,
div.pure-u.sidebar,
div.q0b9qr-2.kqgrGb,
div.q0b9qr-3,
div.quick-navs,
div.quickMenu,
div.read-btn.mobile-hide,
div.rf-main-visual,
div.rm-footer,
div.row.member-text,
div.row.text-center,
div.rss,
div.s17ljdfo-0,
div.sc-1x15mdy-3.sc-1x15mdy-4.cyMsTb.cijtNn,
div.sc-1x15mdy-3.sc-1x15mdy-4.gvHsew.fagTCQ,
div.sc-3lap54-1.ifWCni,
div.sc-4ev7nz-0.l7v9z99,
div.sc-bHwgHz.hNbkab,
div.search-load,
div.sharedaddy.sd-sharing-enabled,
div.sidebar.s1,
div.sidebar_inner.fixed-me,
div.sidebar_list li,
div.six.columns.clearfix,
div.smartbanner--ios,
div.sns_frame_small,
div.stick-progress,
div.stick-share,
div.subfooter-menu-holder.text-center,
div.tenki-ad-lite-north,
div.tenki-ad-lite-overlay,
div.tg-content,
div.title1.txt1.col-xs-12.pull-left,
div.top-navigation,
div.topics,
div.topics-inner-img,
div.topics-txt-page,
div.topics-txt-page>ul,
div.ult__mods.JnVVZlSIAMbTJUrCMznTu,
div.virus__section.clearfix,
div.wpa,
div.zGtbP,
div[data-v-3b5521dd],
div[data-widget_type="share-buttons.default"],
div[style].cc-grower,
dl.checkOther,
dl.rf-list-side-items,
footer a.sportihealth-Logo,
footer#colophon,
footer.article__footer,
footer.commonFooter,
footer.footer-menu,
footer.modFooter,
footer.uf-footer,
footer>div.footer_nav,
form.js-search-form,
gpt_ads_bg,
h2.h2>span,
h2.hN,
h2.is-ttl,
h2.signle-h2,
header._2W05UT36._3e-Y2Bts,
header.sticky-jump,
header>div.block,
hr.wp-block-separator,
iframe#comment-plugin,
li.googleAds-style-stylelist-sp-native-wrap,
nav#portal_menu,
nav._3FP2YQBl,
nav.c-breadcrumbs,
nav.nav-footer.container,
nav.social-widget,
p#ofr i,
p.pvc_stats.pvc_load_by_ajax_update,
section#ai_widget-2,
section#log-rsab,
section#member-area,
section#section-bar,
section.ad-zone-mobile,
section.bg--gray,
section.bg--orange,
section.cw__advertising,
section.discover-stream,
section.gray-border--bottom,
section.index-books,
section.js-booking-toast-message,
section.modSpecial,
section.related-article.break,
section.s1l33al0-0,
section.site-sns,
section.subscribe-area,
section>ul.rf-list-items,
span.dpwska-0,
ul#adx_container,
ul.areanav.clearfix,
ul.c-choice-list,
ul.juiz_sps_links_list.juiz_sps_hide_name,
ul.modSocial_btn,
ul.section-horizontal-list.inner,
ul.shareBar__info--push,
ul.sns-label__list,
ul.solo_contents_list,
ul.wp-block-latest-posts.wp-block-latest-posts__list {

    display: none !important;
    height: 0px !important;

}


  `;
  document.head.appendChild(style);
}());
